services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file: ".env"
    ports:
      - "5672:5672" # AMQP apps
      - "15672:15672" # UI admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - CoreTeam-network
    restart: unless-stopped

  mi-postgres:
    image: postgres:16
    container_name: CoreTeam-postgres
    env_file: ".env"
    networks:
      - CoreTeam-network
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: CoreTeam-pgadmin
    env_file: ".env"
    networks:
      - CoreTeam-network
    ports:
      - "8080:80"
    depends_on:
      - mi-postgres
    restart: unless-stopped

  # app:
  #   image: core-backend:latest
  #   env_file: ".env"
  #   container_name: CoreTeam-app
  #   networks:
  #     - CoreTeam-network
  #   ports:
  #     - "3030:3030"
  #   depends_on:
  #     - rabbitmq
  #     - mi-postgres
  #   restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  CoreTeam-network:
    driver: bridge
