name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Info
        run: |
          echo "Deployed by: ${{ github.actor }}"
          echo "Target branch: ${{ github.ref_name }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key with passphrase
        run: |
          echo "${{ secrets.DO_SSH_KEY }}" > private_key
          chmod 600 private_key
          eval "$(ssh-agent -s)"
          ssh-add private_key

      - name: Deploy to Digital Ocean
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.DO_CONNECTION_URI }} "
            if [ ! -d ~/core-backend ]; then
              git clone https://github.com/gregoriocarranza/WonderPeak_backend.git ~/core-backend
            else
              cd ~/core-backend && git pull
            fi
            cd ~/core-backend
            echo \"${ENV_FILE_CONTENT}\" > .env
            docker stop $(docker ps -aq)
            docker compose up --build -d
          "

      - name: Clean up SSH key
        if: always()
        run: |
          eval "$(ssh-agent -s)"
          ssh-add -D
          rm -f private_key